// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1GCGGZszy0EZah9rJPw2iRMB07HIpBk0',
    appId: '1:376956967576:web:2cb3961ad65633eb498eed',
    messagingSenderId: '376956967576',
    projectId: 'dart-package-dashboard',
    authDomain: 'dart-package-dashboard.firebaseapp.com',
    storageBucket: 'dart-package-dashboard.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcP0xgXO-ZxOAZZez7DYJQhB5C3nxTx_o',
    appId: '1:376956967576:ios:921a3de01ee30736498eed',
    messagingSenderId: '376956967576',
    projectId: 'dart-package-dashboard',
    storageBucket: 'dart-package-dashboard.appspot.com',
    iosClientId:
        '376956967576-1rai17ahple8tpfqlogqngoqnvgdbeen.apps.googleusercontent.com',
    iosBundleId: 'com.example.packagesWeb',
  );
}
